esphome:
  name: matrix-display
  platformio_options:
    lib_deps:
      - SPI
      - Wire
      - Adafruit BusIO
      - adafruit/Adafruit GFX Library
      - https://github.com/Rafit77/ESP32-HUB75-MatrixPanel-DMA#master

display:
  - platform: hub75_matrix_display
    id: matrix
    width: 64
    height: 32
    use_custom_library: true
